#!/usr/bin/env bash
#
# cmux post-create hook — initializes a freshly-created feature worktree.
# Invoked by /cmux:start-feature with cwd = feature worktree.
#
# Env exported by cmux:
#   CMUX_FEATURE_SLUG     — short slug, e.g. "auth-jwt"
#   CMUX_FEATURE_BRANCH   — "feature/<slug>"
#   CMUX_FEATURE_WORKTREE — absolute path of the new worktree
#   CMUX_MAIN_WORKTREE    — absolute path of the main worktree

set -euo pipefail

log() {
  printf '[post-create] %s\n' "$*"
  if command -v cmux >/dev/null 2>&1 && [ -n "${CMUX_WORKSPACE_ID:-}" ]; then
    cmux log --level progress --source "post-create" -- "$*" \
      >/dev/null 2>&1 || true
  fi
}

log "Initializing feature/${CMUX_FEATURE_SLUG:-?} in $(pwd)"

# Frontend — node_modules/ is gitignored, so each worktree needs its own
# install. corepack pins the pnpm version declared in package.json.
if [ -f frontend/package.json ]; then
  log "Enabling pnpm via corepack"
  corepack enable >/dev/null 2>&1 || true

  log "Installing frontend dependencies"
  cd frontend
  pnpm install --frozen-lockfile
  cd ..
fi

# Workers — pre-warm the Go module cache so the first build/run in this
# worktree does not stall on network.
if [ -f workers/go.mod ]; then
  log "Downloading Go modules"
  cd workers
  go mod download
  cd ..
fi

# Compose host-port remapping — so several cmux worktrees can run the full
# stack at once without fighting over the same host ports. cmux gives each
# workspace a contiguous port block starting at $CMUX_PORT (ending at
# $CMUX_PORT_END); we publish the whole stack inside that block.
#
# `!override` REPLACES the base `ports:` list. Compose concatenates
# multi-value options by default, so a plain override would re-bind the
# original 3000/7233/8233/... and defeat the isolation. The file is
# per-worktree and gitignored — it is never committed.
if [ -f compose.yaml ] && [ -n "${CMUX_PORT:-}" ]; then
  if printf '%s' "$CMUX_PORT" | grep -qE '^[0-9]+$'; then
    base="$CMUX_PORT"
    web=$base                 # frontend (web UI)  -> CMUX_PORT
    grpc=$((base + 1))        # temporal gRPC      -> CMUX_PORT+1
    ui=$((base + 2))          # temporal web UI    -> CMUX_PORT+2
    nats_port=$((base + 3))   # nats client        -> CMUX_PORT+3
    codec=$((base + 4))       # codec server       -> CMUX_PORT+4

    if [ -n "${CMUX_PORT_END:-}" ] && [ "$codec" -gt "$CMUX_PORT_END" ]; then
      log "WARNING: port block ${base}..${codec} exceeds" \
        "CMUX_PORT_END=${CMUX_PORT_END}"
    fi

    log "Writing compose.override.yaml (host ports ${base}..${codec})"
    cat > compose.override.yaml <<EOF
# Generated by .cmux/post-create.sh for cmux workspace port isolation.
# DO NOT COMMIT — specific to this worktree's CMUX_PORT block.
#
# Host-side ports are derived from CMUX_PORT (this workspace: ${base}):
#   frontend  web UI  -> http://localhost:${web}
#   temporal  gRPC    -> ${grpc}
#   temporal  web UI  -> http://localhost:${ui}
#   nats      client  -> ${nats_port}
#   codec     server  -> ${codec}
#
# \`!override\` fully replaces the base ports list (Compose concatenates
# multi-value options by default, which would re-publish the originals).
services:
  frontend:
    ports: !override
      - "${web}:3000"
  temporal:
    ports: !override
      - "${grpc}:7233"
      - "${ui}:8233"
  nats:
    ports: !override
      - "${nats_port}:4222"
  codec-server:
    ports: !override
      - "${codec}:8888"
    # The codec server only accepts /decode calls from the Temporal Web UI's
    # origin; follow the remapped UI port so the codec demo keeps working.
    environment:
      UI_ORIGIN: "http://localhost:${ui},http://127.0.0.1:${ui}"
EOF
  else
    log "CMUX_PORT='${CMUX_PORT}' is not numeric — skipping override"
  fi
else
  [ -n "${CMUX_PORT:-}" ] || log "CMUX_PORT unset — skipping compose.override.yaml"
fi

log "Done"
