.DEFAULT_GOAL := app-up

# Per-worktree dev-mode port isolation. When Casper assigns this workspace a
# CASPER_PORT, `make bootstrap` remaps the container host ports (see
# compose.override.yaml); mirror that for the host-run dev processes so several
# worktrees can `make dev` at once. The frontend listens on CASPER_PORT and
# both frontend and workers reach the remapped infra (temporal +1, nats +3).
# Unset CASPER_PORT keeps the default ports. compose.yaml hardcodes the
# in-container addresses, so exporting these never affects the containers.
ifneq ($(CASPER_PORT),)
export PORT             := $(CASPER_PORT)
export TEMPORAL_ADDRESS := localhost:$(shell expr $(CASPER_PORT) + 1)
export NATS_URL         := nats://localhost:$(shell expr $(CASPER_PORT) + 3)
endif

##@ Infra

.PHONY: infra-up
infra-up: ## Start local Temporal server and NATS (docker-compose)
	docker-compose up -d temporal nats

.PHONY: infra-down
infra-down: ## Stop local Temporal server and NATS
	docker-compose stop temporal nats

.PHONY: infra-logs
infra-logs: ## Follow Temporal server logs
	docker-compose logs -f temporal

##@ App

.PHONY: app-up
app-up: ## Build and run the full stack (infra, frontend, workers) in containers
	docker-compose up -d

.PHONY: app-down
app-down: ## Stop the full stack and remove containers
	docker-compose down

.PHONY: app-logs
app-logs: ## Follow logs from every container
	docker-compose logs -f

##@ Modules

.PHONY: frontend
frontend: ## Run the frontend dev server
	$(MAKE) -C frontend dev

.PHONY: worker-%
worker-%: ## Run a pattern worker (e.g. make worker-saga)
	$(MAKE) -C workers run-$*

.PHONY: dev-workers
dev-workers: ## Run every pattern worker with hot-reload (requires Air)
	$(MAKE) -C workers dev-all

.PHONY: dev
dev: infra-up ## Start infra, then run the frontend and all workers in parallel with hot-reload
	@$(MAKE) -j frontend dev-workers

.PHONY: check
check: ## Run all checks across modules
	$(MAKE) -C frontend check
	$(MAKE) -C workers check

.PHONY: setup
setup: ## Install the versioned git hooks (one-time, per clone)
	git config core.hooksPath .githooks
	@echo "git hooks: core.hooksPath -> .githooks"

##@ Workspace

.PHONY: bootstrap
bootstrap: ## Prepare a fresh worktree: install deps and pin container host ports to $CASPER_PORT
	cd frontend && corepack enable && pnpm install --frozen-lockfile
	cd workers && go mod download
	@base="$${CASPER_PORT:-}"; \
	case "$$base" in \
		"" ) echo "CASPER_PORT unset — keeping default host ports"; exit 0 ;; \
		*[!0-9]* ) echo "CASPER_PORT='$$base' is not numeric — keeping default host ports"; exit 0 ;; \
	esac; \
	echo "Pinning host ports to $$base..$$((base+4)) in compose.override.yaml"; \
	{ \
		echo "# Generated by 'make bootstrap' from CASPER_PORT — DO NOT COMMIT (gitignored)."; \
		echo "# '!override' replaces the base ports list (Compose concatenates by default)."; \
		echo "services:"; \
		echo "  frontend:"; \
		echo "    ports: !override [\"$$base:3000\"]"; \
		echo "  temporal:"; \
		echo "    ports: !override [\"$$((base+1)):7233\", \"$$((base+2)):8233\"]"; \
		echo "  nats:"; \
		echo "    ports: !override [\"$$((base+3)):4222\"]"; \
		echo "  codec-server:"; \
		echo "    ports: !override [\"$$((base+4)):8888\"]"; \
		echo "    environment:"; \
		echo "      UI_ORIGIN: \"http://localhost:$$((base+2)),http://127.0.0.1:$$((base+2))\""; \
	} > compose.override.yaml

.PHONY: teardown
teardown: ## Stop this worktree's containers
	docker-compose down

##@ Helpers

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(MAKEFILE_LIST)
