<script setup lang="ts">
import { computed } from "vue";
import type { EventEnvelope } from "~~/shared/events";
import type { CodeLang } from "~/composables/useCodeLang";
import type { CodeSource } from "~/types/code-viewer";

type HighlightKey =
  | "validate-item"
  | "price-item"
  | "update-qty"
  | "remove-item"
  | "process-payment"
  | "send-confirmation"
  | "getCart";

interface EntitySource extends CodeSource {
  hl: Record<HighlightKey, [number, number]>;
}

const props = defineProps<{
  events: EventEnvelope[];
}>();

const lang = useCodeLang();

const SOURCES: Record<CodeLang, EntitySource> = {
  go: {
    label: "Go",
    lines: [
      "func ShoppingCartWorkflow(ctx workflow.Context, state CartState) error {",
      "    ctx = workflow.WithActivityOptions(ctx, workflow.ActivityOptions{",
      "        StartToCloseTimeout: 5 * time.Second,",
      "    })",
      "    // Catalog and pricing backends are flaky: short timeout, retry forever.",
      "    flakeyCtx := workflow.WithActivityOptions(ctx, workflow.ActivityOptions{",
      "        StartToCloseTimeout: 1500 * time.Millisecond,",
      "        RetryPolicy: &temporal.RetryPolicy{",
      "            InitialInterval:    200 * time.Millisecond,",
      "            BackoffCoefficient: 1.5,",
      "            MaximumInterval:    time.Second,",
      "        },",
      "    })",
      '    addCh := workflow.GetSignalChannel(ctx, "addItem")',
      '    updateCh := workflow.GetSignalChannel(ctx, "updateQty")',
      '    removeCh := workflow.GetSignalChannel(ctx, "removeItem")',
      '    checkoutCh := workflow.GetSignalChannel(ctx, "checkout")',
      "",
      '    workflow.SetQueryHandler(ctx, "getCart", func() (Progress, error) {',
      "        state.QueriesAnswered++ // advisory UI counter",
      "        return toProgress(state,",
      "            workflow.GetInfo(ctx).GetCurrentHistoryLength()), nil",
      "    })",
      "",
      "    var a *Activities",
      "    for !state.CheckedOut {",
      "        sel := workflow.NewSelector(ctx)",
      "",
      "        sel.AddReceive(addCh, func(ch workflow.ReceiveChannel, _ bool) {",
      "            var sig AddItemSignal",
      "            ch.Receive(ctx, &sig)",
      "            workflow.ExecuteActivity(flakeyCtx, a.ValidateItem, sig).Get(ctx, nil) // errors elided for brevity",
      "            workflow.ExecuteActivity(flakeyCtx, a.PriceItem, sig).Get(ctx, nil)",
      "            state = applyAdd(state, sig)",
      "        })",
      "",
      "        sel.AddReceive(updateCh, func(ch workflow.ReceiveChannel, _ bool) {",
      "            var sig UpdateQtySignal",
      "            ch.Receive(ctx, &sig)",
      "            workflow.ExecuteActivity(ctx, a.UpdateQty, sig).Get(ctx, nil)",
      "            state = applyUpdate(state, sig)",
      "        })",
      "",
      "        sel.AddReceive(removeCh, func(ch workflow.ReceiveChannel, _ bool) {",
      "            var sig RemoveItemSignal",
      "            ch.Receive(ctx, &sig)",
      "            workflow.ExecuteActivity(ctx, a.RemoveItem, sig).Get(ctx, nil)",
      "            state = applyRemove(state, sig)",
      "        })",
      "",
      "        sel.AddReceive(checkoutCh, func(ch workflow.ReceiveChannel, _ bool) {",
      "            var sig CheckoutSignal",
      "            ch.Receive(ctx, &sig)",
      "            var orderID string",
      "            workflow.ExecuteActivity(ctx,",
      "                a.ProcessPayment, state.CartID, total(state),",
      "            ).Get(ctx, &orderID)",
      "            workflow.ExecuteActivity(ctx,",
      "                a.SendConfirmation, state.CartID, orderID,",
      "            ).Get(ctx, nil)",
      "            state.CheckedOut = true",
      "        })",
      "",
      "        sel.Select(ctx)",
      "        state.SignalsReceived++",
      "    }",
      "    return nil",
      "}",
    ],
    hl: {
      "validate-item": [31, 31],
      "price-item": [32, 32],
      "update-qty": [39, 39],
      "remove-item": [46, 46],
      "process-payment": [53, 56],
      "send-confirmation": [57, 59],
      getCart: [18, 22],
    },
  },
  java: {
    label: "Java",
    lines: [
      "@WorkflowInterface",
      "public interface ShoppingCartWorkflow {",
      "    @WorkflowMethod",
      "    void run(CartState initial);",
      "",
      '    @SignalMethod(name = "addItem")',
      "    void addItem(AddItemSignal sig);",
      "",
      '    @SignalMethod(name = "updateQty")',
      "    void updateQty(UpdateQtySignal sig);",
      "",
      '    @SignalMethod(name = "removeItem")',
      "    void removeItem(RemoveItemSignal sig);",
      "",
      '    @SignalMethod(name = "checkout")',
      "    void checkout();",
      "",
      '    @QueryMethod(name = "getCart")',
      "    Progress getCart();",
      "}",
      "",
      "sealed interface Signal permits AddItemSignal, UpdateQtySignal, RemoveItemSignal, CheckoutSignal {}",
      "",
      "public class ShoppingCartWorkflowImpl implements ShoppingCartWorkflow {",
      "    private final Deque<Signal> inbox = new ArrayDeque<>();",
      "    private CartState state;",
      "    private final Activities activities = Workflow.newActivityStub(",
      "        Activities.class,",
      "        ActivityOptions.newBuilder().setStartToCloseTimeout(Duration.ofSeconds(5)).build());",
      "    // Catalog and pricing backends are flaky: short timeout, retry forever.",
      "    private final Activities flakeyActivities = Workflow.newActivityStub(",
      "        Activities.class,",
      "        ActivityOptions.newBuilder()",
      "            .setStartToCloseTimeout(Duration.ofMillis(1500))",
      "            .setRetryOptions(RetryOptions.newBuilder()",
      "                .setInitialInterval(Duration.ofMillis(200))",
      "                .setBackoffCoefficient(1.5)",
      "                .setMaximumInterval(Duration.ofSeconds(1))",
      "                .build())",
      "            .build());",
      "",
      "    @Override",
      "    public void run(CartState initial) {",
      "        state = initial;",
      "        while (!state.checkedOut()) {",
      "            Workflow.await(() -> !inbox.isEmpty());",
      "            var sig = inbox.removeFirst();",
      "            switch (sig) {",
      "                case AddItemSignal s -> {",
      "                    flakeyActivities.validateItem(s);",
      "                    flakeyActivities.priceItem(s);",
      "                    state = applyAdd(state, s);",
      "                }",
      "                case UpdateQtySignal s -> {",
      "                    activities.updateQty(s);",
      "                    state = applyUpdate(state, s);",
      "                }",
      "                case RemoveItemSignal s -> {",
      "                    activities.removeItem(s);",
      "                    state = applyRemove(state, s);",
      "                }",
      "                case CheckoutSignal s -> {",
      "                    String orderId = activities.processPayment(",
      "                        state.cartId(), total(state));",
      "                    activities.sendConfirmation(state.cartId(), orderId);",
      "                    state = state.withCheckedOut(true);",
      "                }",
      "            }",
      "            state = state.bumpSignals();",
      "        }",
      "    }",
      "",
      "    @Override",
      "    public void addItem(AddItemSignal sig) { inbox.add(sig); }",
      "",
      "    @Override",
      "    public void updateQty(UpdateQtySignal sig) { inbox.add(sig); }",
      "",
      "    @Override",
      "    public void removeItem(RemoveItemSignal sig) { inbox.add(sig); }",
      "",
      "    @Override",
      "    public void checkout() { inbox.add(new CheckoutSignal()); }",
      "",
      "    @Override",
      "    public Progress getCart() {",
      "        state = state.bumpQueries(); // advisory UI counter",
      "        return toProgress(state,",
      "            Workflow.getInfo().getHistoryLength());",
      "    }",
      "}",
    ],
    hl: {
      "validate-item": [49, 49],
      "price-item": [50, 50],
      "update-qty": [54, 54],
      "remove-item": [58, 58],
      "process-payment": [62, 63],
      "send-confirmation": [64, 64],
      getCart: [84, 89],
    },
  },
  typescript: {
    label: "TypeScript",
    lines: [
      "import {",
      "    proxyActivities, defineSignal, defineQuery,",
      "    setHandler, condition, workflowInfo,",
      '} from "@temporalio/workflow";',
      'import type * as activities from "./activities";',
      "",
      "const a = proxyActivities<typeof activities>({",
      '    startToCloseTimeout: "5 seconds",',
      "});",
      "",
      "// Catalog and pricing backends are flaky: short timeout, retry forever.",
      "const flakey = proxyActivities<typeof activities>({",
      '    startToCloseTimeout: "1500 ms",',
      '    retry: { initialInterval: "200 ms", backoffCoefficient: 1.5, maximumInterval: "1 second" },',
      "});",
      "",
      'export const addItem = defineSignal<[AddItemSignal]>("addItem");',
      'export const updateQty = defineSignal<[UpdateQtySignal]>("updateQty");',
      'export const removeItem = defineSignal<[RemoveItemSignal]>("removeItem");',
      'export const checkout = defineSignal<[]>("checkout");',
      'export const getCart = defineQuery<Progress>("getCart");',
      "",
      "export async function shoppingCartWorkflow(state: CartState): Promise<void> {",
      "    const inbox: Signal[] = [];",
      '    setHandler(addItem, (s) => { inbox.push({ kind: "add", sig: s }); });',
      '    setHandler(updateQty, (s) => { inbox.push({ kind: "update", sig: s }); });',
      '    setHandler(removeItem, (s) => { inbox.push({ kind: "remove", sig: s }); });',
      '    setHandler(checkout, () => { inbox.push({ kind: "checkout" }); });',
      "",
      "    setHandler(getCart, () => {",
      "        state = { ...state, queriesAnswered: state.queriesAnswered + 1 }; // advisory UI counter",
      "        return toProgress(state, workflowInfo().historyLength);",
      "    });",
      "",
      "    while (!state.checkedOut) {",
      "        await condition(() => inbox.length > 0);",
      "        const sig = inbox.shift()!;",
      "        switch (sig.kind) {",
      '            case "add":',
      "                await flakey.validateItem(sig.sig);",
      "                await flakey.priceItem(sig.sig);",
      "                state = applyAdd(state, sig.sig);",
      "                break;",
      '            case "update":',
      "                await a.updateQty(sig.sig);",
      "                state = applyUpdate(state, sig.sig);",
      "                break;",
      '            case "remove":',
      "                await a.removeItem(sig.sig);",
      "                state = applyRemove(state, sig.sig);",
      "                break;",
      '            case "checkout": {',
      "                const orderId = await a.processPayment(",
      "                    state.cartId, total(state));",
      "                await a.sendConfirmation(state.cartId, orderId);",
      "                state = { ...state, checkedOut: true };",
      "                break;",
      "            }",
      "        }",
      "        state = { ...state, signalsReceived: state.signalsReceived + 1 };",
      "    }",
      "}",
    ],
    hl: {
      "validate-item": [39, 39],
      "price-item": [40, 40],
      "update-qty": [44, 44],
      "remove-item": [48, 48],
      "process-payment": [52, 53],
      "send-confirmation": [54, 54],
      getCart: [29, 32],
    },
  },
  python: {
    label: "Python",
    lines: [
      "# Catalog and pricing backends are flaky: short timeout, retry forever.",
      "FLAKEY_TIMEOUT = timedelta(milliseconds=1500)",
      "FLAKEY_RETRY = RetryPolicy(",
      "    initial_interval=timedelta(milliseconds=200),",
      "    backoff_coefficient=1.5,",
      "    maximum_interval=timedelta(seconds=1),",
      ")",
      "",
      "",
      "@workflow.defn",
      "class ShoppingCartWorkflow:",
      "    @workflow.init",
      "    def __init__(self, initial: CartState) -> None:",
      "        self._inbox: list[tuple[str, Any]] = []",
      "        self._state = initial",
      "",
      '    @workflow.signal(name="addItem")',
      "    def add_item(self, sig: AddItemSignal) -> None:",
      '        self._inbox.append(("add", sig))',
      "",
      '    @workflow.signal(name="updateQty")',
      "    def update_qty(self, sig: UpdateQtySignal) -> None:",
      '        self._inbox.append(("update", sig))',
      "",
      '    @workflow.signal(name="removeItem")',
      "    def remove_item(self, sig: RemoveItemSignal) -> None:",
      '        self._inbox.append(("remove", sig))',
      "",
      '    @workflow.signal(name="checkout")',
      "    def checkout(self) -> None:",
      '        self._inbox.append(("checkout", None))',
      "",
      '    @workflow.query(name="getCart")',
      "    def get_cart(self) -> Progress:",
      "        self._state = self._state.bump_queries()  # advisory UI counter",
      "        return to_progress(self._state, workflow.info().get_current_history_length())",
      "",
      "    @workflow.run",
      "    async def run(self, initial: CartState) -> None:",
      "        while not self._state.checked_out:",
      "            await workflow.wait_condition(lambda: len(self._inbox) > 0)",
      "            kind, sig = self._inbox.pop(0)",
      '            if kind == "add":',
      "                await workflow.execute_activity(validate_item, sig,",
      "                    start_to_close_timeout=FLAKEY_TIMEOUT, retry_policy=FLAKEY_RETRY)",
      "                await workflow.execute_activity(price_item, sig,",
      "                    start_to_close_timeout=FLAKEY_TIMEOUT, retry_policy=FLAKEY_RETRY)",
      "                self._state = apply_add(self._state, sig)",
      '            elif kind == "update":',
      "                await workflow.execute_activity(update_qty, sig,",
      "                    start_to_close_timeout=timedelta(seconds=5))",
      "                self._state = apply_update(self._state, sig)",
      '            elif kind == "remove":',
      "                await workflow.execute_activity(remove_item, sig,",
      "                    start_to_close_timeout=timedelta(seconds=5))",
      "                self._state = apply_remove(self._state, sig)",
      '            elif kind == "checkout":',
      "                order_id = await workflow.execute_activity(",
      "                    process_payment, args=[self._state.cart_id, total(self._state)],",
      "                    start_to_close_timeout=timedelta(seconds=5))",
      "                await workflow.execute_activity(",
      "                    send_confirmation, args=[self._state.cart_id, order_id],",
      "                    start_to_close_timeout=timedelta(seconds=5))",
      "                self._state = self._state.with_checked_out()",
      "            self._state = self._state.bump_signals()",
    ],
    hl: {
      "validate-item": [43, 44],
      "price-item": [45, 46],
      "update-qty": [49, 50],
      "remove-item": [53, 54],
      "process-payment": [57, 59],
      "send-confirmation": [60, 62],
      getCart: [32, 35],
    },
  },
};

const CHECKOUT_STEPS: ReadonlySet<string> = new Set(["process-payment", "send-confirmation"]);

function stepOf(env: EventEnvelope): string {
  return String((env.data as Record<string, unknown>).step ?? "");
}

const highlight = computed<[number, number] | null>(() => {
  const src = SOURCES[lang.value];

  for (let i = props.events.length - 1; i >= 0; i--) {
    const env = props.events[i];
    if (!env) continue;

    if (env.type === "progress.workflow.completed" || env.type === "progress.workflow.failed") {
      // Keep the last checkout step highlighted so viewers see where the
      // workflow returned rather than jumping back to the top on success.
      const checkoutRan = props.events.some(
        (e) => e.type === "progress.step.completed" && CHECKOUT_STEPS.has(stepOf(e)),
      );
      return checkoutRan ? src.hl["send-confirmation"] : null;
    }
    // Synthetic envelope pushed by the page when it issues a getCart query.
    if (env.type === "entity.query.getCart") {
      return src.hl["getCart"];
    }
    if (env.type === "progress.step.started" || env.type === "progress.step.failed") {
      const step = stepOf(env);
      if (step !== "getCart" && Object.hasOwn(src.hl, step)) {
        return src.hl[step as HighlightKey];
      }
    }
  }
  return null;
});
</script>

<template>
  <CodeViewer :sources="SOURCES" :highlight="highlight" />
</template>
