<script setup lang="ts">
import { computed } from "vue";
import type { EventEnvelope } from "~~/shared/events";
import type { CodeLang } from "~/composables/useCodeLang";
import type { CodeSource } from "~/types/code-viewer";

type StepKey = "plan" | "queries" | "fanout" | "search" | "fanin" | "synth";

interface MultiAgentSource extends CodeSource {
  stepLines: Record<StepKey, [number, number]>;
}

const props = defineProps<{
  events: EventEnvelope[];
}>();

const SOURCES: Record<CodeLang, MultiAgentSource> = {
  go: {
    label: "Go",
    lines: [
      "func DeepResearchWorkflow(ctx workflow.Context, req DeepResearchRequest) (Report, error) {",
      "    ctx = workflow.WithActivityOptions(ctx, workflow.ActivityOptions{",
      "        StartToCloseTimeout: 10 * time.Second,",
      "    })",
      "    var a *Activities",
      "",
      "    // Phase 1 — Plan: LLM decomposes the prompt into subtopics.",
      "    var plan ResearchPlan",
      "    if err := workflow.ExecuteActivity(ctx, a.PlanResearch, req).",
      "        Get(ctx, &plan); err != nil {",
      "        return Report{}, err",
      "    }",
      "",
      "    // Phase 2 — Query gen: one LLM call per subtopic.",
      "    var queries ResearchQueries",
      "    if err := workflow.ExecuteActivity(ctx, a.GenerateQueries, plan).",
      "        Get(ctx, &queries); err != nil {",
      "        return Report{}, err",
      "    }",
      "",
      "    // Phase 3 — Fan-out: one child workflow per subtopic.",
      "    futures := make([]workflow.ChildWorkflowFuture, len(queries.Topics))",
      "    for i, tq := range queries.Topics {",
      "        futures[i] = workflow.ExecuteChildWorkflow(ctx, ResearchAgentWorkflow,",
      "            ResearchAgentInput{TopicIndex: tq.TopicIndex,",
      "                TopicName: tq.TopicName, Queries: tq.Queries})",
      "    }",
      "",
      "    // Fan-in: tolerate per-child failures.",
      "    var ok []ResearchResult",
      "    for _, f := range futures {",
      "        var r ResearchResult",
      "        if err := f.Get(ctx, &r); err == nil {",
      "            ok = append(ok, r)",
      "        }",
      "    }",
      "    if len(ok) == 0 {",
      "        return Report{}, temporal.NewNonRetryableApplicationError(",
      '            "every research agent failed", "AllChildrenFailed", nil)',
      "    }",
      "",
      "    // Phase 4 — Synthesis: LLM merges the surviving results.",
      "    var report Report",
      "    if err := workflow.ExecuteActivity(ctx, a.SynthesizeReport,",
      "        SynthesisInput{Prompt: req.Prompt, Results: ok}).",
      "        Get(ctx, &report); err != nil {",
      "        return Report{}, err",
      "    }",
      "    return report, nil",
      "}",
      "",
      "func ResearchAgentWorkflow(ctx workflow.Context, in ResearchAgentInput) (ResearchResult, error) {",
      "    ctx = workflow.WithActivityOptions(ctx, workflow.ActivityOptions{",
      "        StartToCloseTimeout: 10 * time.Second,",
      "    })",
      "    var a *Activities",
      "    result := ResearchResult{TopicIndex: in.TopicIndex, TopicName: in.TopicName}",
      "    failed := 0",
      "    for qi, q := range in.Queries {",
      "        var sr SearchResult",
      "        if err := workflow.ExecuteActivity(ctx, a.WebSearch,",
      "            SearchInput{TopicIndex: in.TopicIndex, QueryIndex: qi, Query: q}).",
      "            Get(ctx, &sr); err != nil {",
      "            failed++",
      "            continue",
      "        }",
      "        result.Sources = append(result.Sources, sr.Sources...)",
      "    }",
      "    if failed == len(in.Queries) {",
      "        return ResearchResult{}, temporal.NewNonRetryableApplicationError(",
      '            "all searches failed", "AllSearchesFailed", nil)',
      "    }",
      "    result.Partial = failed > 0",
      "    return result, nil",
      "}",
    ],
    stepLines: {
      plan: [6, 11],
      queries: [13, 18],
      fanout: [20, 26],
      fanin: [28, 39],
      synth: [41, 48],
      search: [56, 73],
    },
  },
  java: {
    label: "Java",
    lines: [
      "private final ResearchActivities activities = Workflow.newActivityStub(",
      "    ResearchActivities.class,",
      "    ActivityOptions.newBuilder()",
      "        .setStartToCloseTimeout(Duration.ofSeconds(10))",
      "        .build());",
      "",
      "@Override",
      "public Report deepResearch(DeepResearchRequest req) {",
      "    // Phase 1 — Plan: LLM decomposes the prompt into subtopics.",
      "    ResearchPlan plan = activities.planResearch(req);",
      "",
      "    // Phase 2 — Query gen: one LLM call per subtopic.",
      "    ResearchQueries queries = activities.generateQueries(plan);",
      "",
      "    // Phase 3 — Fan-out: one child workflow per subtopic.",
      "    var futures = new ArrayList<Promise<ResearchResult>>();",
      "    for (var tq : queries.topics()) {",
      "        var child = Workflow.newChildWorkflowStub(ResearchAgentWorkflow.class);",
      "        futures.add(Async.function(child::researchAgent,",
      "            new ResearchAgentInput(tq.topicIndex(), tq.topicName(), tq.queries())));",
      "    }",
      "",
      "    // Fan-in: tolerate per-child failures.",
      "    var ok = new ArrayList<ResearchResult>();",
      "    for (var f : futures) {",
      "        try {",
      "            ok.add(f.get());",
      "        } catch (ChildWorkflowFailure e) {",
      "            // skip the failed child",
      "        }",
      "    }",
      "    if (ok.isEmpty()) {",
      "        throw ApplicationFailure.newNonRetryableFailure(",
      '            "every research agent failed", "AllChildrenFailed");',
      "    }",
      "",
      "    // Phase 4 — Synthesis: LLM merges the surviving results.",
      "    return activities.synthesizeReport(",
      "        new SynthesisInput(req.prompt(), ok));",
      "}",
      "",
      "// ResearchAgentWorkflowImpl — a separate class with the same activities stub",
      "@Override",
      "public ResearchResult researchAgent(ResearchAgentInput in) {",
      "    var result = new ResearchResult(in.topicIndex(), in.topicName());",
      "    int failed = 0;",
      "    for (int qi = 0; qi < in.queries().size(); qi++) {",
      "        try {",
      "            var sr = activities.webSearch(",
      "                new SearchInput(in.topicIndex(), qi, in.queries().get(qi)));",
      "            result.addSources(sr.sources());",
      "        } catch (ActivityFailure e) {",
      "            failed++;",
      "        }",
      "    }",
      "    if (failed == in.queries().size()) {",
      "        throw ApplicationFailure.newNonRetryableFailure(",
      '            "all searches failed", "AllSearchesFailed");',
      "    }",
      "    result.setPartial(failed > 0);",
      "    return result;",
      "}",
    ],
    stepLines: {
      plan: [8, 9],
      queries: [11, 12],
      fanout: [14, 20],
      fanin: [22, 34],
      synth: [36, 38],
      search: [44, 60],
    },
  },
  typescript: {
    label: "TypeScript",
    lines: [
      "import {",
      "    ActivityFailure, ApplicationFailure, executeChild, proxyActivities,",
      '} from "@temporalio/workflow";',
      'import type * as activities from "./activities";',
      "",
      "const a = proxyActivities<typeof activities>({",
      '    startToCloseTimeout: "10 seconds",',
      "});",
      "",
      "export async function deepResearchWorkflow(req: DeepResearchRequest): Promise<Report> {",
      "    // Phase 1 — Plan: LLM decomposes the prompt into subtopics.",
      "    const plan = await a.planResearch(req);",
      "",
      "    // Phase 2 — Query gen: one LLM call per subtopic.",
      "    const queries = await a.generateQueries(plan);",
      "",
      "    // Phase 3 — Fan-out: one child workflow per subtopic.",
      "    const futures = queries.topics.map((tq) =>",
      "        executeChild(researchAgentWorkflow, {",
      "            args: [{ topicIndex: tq.topicIndex,",
      "                topicName: tq.topicName, queries: tq.queries }],",
      "        }),",
      "    );",
      "",
      "    // Fan-in: tolerate per-child failures.",
      "    const settled = await Promise.allSettled(futures);",
      "    const ok = settled",
      '        .filter((s): s is PromiseFulfilledResult<ResearchResult> => s.status === "fulfilled")',
      "        .map((s) => s.value);",
      "    if (ok.length === 0) {",
      '        throw ApplicationFailure.nonRetryable("every research agent failed", "AllChildrenFailed");',
      "    }",
      "",
      "    // Phase 4 — Synthesis: LLM merges the surviving results.",
      "    return a.synthesizeReport({ prompt: req.prompt, results: ok });",
      "}",
      "",
      "export async function researchAgentWorkflow(input: ResearchAgentInput): Promise<ResearchResult> {",
      "    const result: ResearchResult = {",
      "        topicIndex: input.topicIndex, topicName: input.topicName,",
      "        sources: [], partial: false,",
      "    };",
      "    let failed = 0;",
      "    for (const [queryIndex, query] of input.queries.entries()) {",
      "        try {",
      "            const sr = await a.webSearch({ topicIndex: input.topicIndex, queryIndex, query });",
      "            result.sources.push(...sr.sources);",
      "        } catch (err) {",
      "            if (!(err instanceof ActivityFailure)) throw err;",
      "            failed++;",
      "        }",
      "    }",
      "    if (failed === input.queries.length) {",
      '        throw ApplicationFailure.nonRetryable("all searches failed", "AllSearchesFailed");',
      "    }",
      "    result.partial = failed > 0;",
      "    return result;",
      "}",
    ],
    stepLines: {
      plan: [10, 11],
      queries: [13, 14],
      fanout: [16, 22],
      fanin: [24, 31],
      synth: [33, 34],
      search: [38, 56],
    },
  },
  python: {
    label: "Python",
    lines: [
      "@workflow.defn",
      "class DeepResearchWorkflow:",
      "    @workflow.run",
      "    async def run(self, req: DeepResearchRequest) -> Report:",
      "        # Phase 1 — Plan: LLM decomposes the prompt into subtopics.",
      "        plan = await workflow.execute_activity(",
      "            plan_research, req,",
      "            start_to_close_timeout=timedelta(seconds=10))",
      "",
      "        # Phase 2 — Query gen: one LLM call per subtopic.",
      "        queries = await workflow.execute_activity(",
      "            generate_queries, plan,",
      "            start_to_close_timeout=timedelta(seconds=10))",
      "",
      "        # Phase 3 — Fan-out: one child workflow per subtopic.",
      "        handles = [",
      "            await workflow.start_child_workflow(",
      "                ResearchAgentWorkflow.run,",
      "                ResearchAgentInput(tq.topic_index, tq.topic_name, tq.queries))",
      "            for tq in queries.topics",
      "        ]",
      "",
      "        # Fan-in: tolerate per-child failures.",
      "        settled = await asyncio.gather(*handles, return_exceptions=True)",
      "        ok = [r for r in settled if not isinstance(r, BaseException)]",
      "        if not ok:",
      "            raise ApplicationError(",
      '                "every research agent failed", type="AllChildrenFailed", non_retryable=True)',
      "",
      "        # Phase 4 — Synthesis: LLM merges the surviving results.",
      "        return await workflow.execute_activity(",
      "            synthesize_report, SynthesisInput(req.prompt, ok),",
      "            start_to_close_timeout=timedelta(seconds=10))",
      "",
      "",
      "@workflow.defn",
      "class ResearchAgentWorkflow:",
      "    @workflow.run",
      "    async def run(self, in_: ResearchAgentInput) -> ResearchResult:",
      "        result = ResearchResult(in_.topic_index, in_.topic_name)",
      "        failed = 0",
      "        for qi, q in enumerate(in_.queries):",
      "            try:",
      "                sr = await workflow.execute_activity(",
      "                    web_search,",
      "                    SearchInput(in_.topic_index, qi, q),",
      "                    start_to_close_timeout=timedelta(seconds=10))",
      "                result.sources.extend(sr.sources)",
      "            except ActivityError:",
      "                failed += 1",
      "        if failed == len(in_.queries):",
      "            raise ApplicationError(",
      '                "all searches failed", type="AllSearchesFailed", non_retryable=True)',
      "        result.partial = failed > 0",
      "        return result",
    ],
    stepLines: {
      plan: [4, 7],
      queries: [9, 12],
      fanout: [14, 20],
      fanin: [22, 27],
      synth: [29, 32],
      search: [39, 54],
    },
  },
};

// Each event type the code viewer reacts to maps to one of the six steps.
// Workflow completion/failure events are skipped on purpose so the last
// step (synth on success, fanin when every child failed) stays highlighted.
const EVENT_TO_STEP: Record<string, StepKey> = {
  "multi-agent.plan.ready": "plan",
  "multi-agent.queries.ready": "queries",
  "multi-agent.fanout.started": "fanout",
  "multi-agent.search.started": "search",
  "multi-agent.search.completed": "search",
  "multi-agent.search.failed": "search",
  "multi-agent.child.completed": "fanin",
  "multi-agent.child.failed": "fanin",
  "multi-agent.report.ready": "synth",
};

const STEP_BY_ACTIVITY: Record<string, StepKey> = {
  "plan-research": "plan",
  "generate-queries": "queries",
  "synthesize-report": "synth",
};

function latestStep(events: EventEnvelope[]): StepKey | null {
  for (let i = events.length - 1; i >= 0; i--) {
    const env = events[i];
    if (!env) continue;

    const eventStep = EVENT_TO_STEP[env.type];
    if (eventStep) return eventStep;

    if (env.type === "progress.step.started" || env.type === "progress.step.completed") {
      const activity = (env.data as Record<string, unknown>).step;
      const activityStep = typeof activity === "string" ? STEP_BY_ACTIVITY[activity] : undefined;
      if (activityStep) return activityStep;
    }
  }
  return null;
}

const lang = useCodeLang();

const currentHighlight = computed<[number, number] | null>(() => {
  const step = latestStep(props.events);
  if (!step) return null;
  return SOURCES[lang.value].stepLines[step];
});
</script>

<template>
  <CodeViewer :sources="SOURCES" :highlight="currentHighlight" />
</template>
