<script setup lang="ts">
import { computed } from "vue";
import type { EventEnvelope } from "~~/shared/events";
import type { CodeLang } from "~/composables/useCodeLang";
import type { CodeSource } from "~/types/code-viewer";

const props = defineProps<{
  events: EventEnvelope[];
}>();

const lang = useCodeLang();

interface SagaSource extends CodeSource {
  stepLines: Record<string, [number, number]>;
  compLines: Record<string, [number, number]>;
}

const SOURCES: Record<CodeLang, SagaSource> = {
  go: {
    label: "Go",
    lines: [
      "func OrderProcessingWorkflow(ctx workflow.Context, input OrderInput) (OrderResult, error) {",
      "    txID := input.TransactionID  // reused on retries — idempotency key",
      "    ctx = workflow.WithActivityOptions(ctx, workflow.ActivityOptions{",
      "        StartToCloseTimeout: 6 * time.Second,",
      "    })",
      "    var a *Activities",
      "    var compensations []func(workflow.Context) error",
      "    result := OrderResult{OrderID: input.OrderID}",
      "",
      "    runCompensations := func() {",
      "        // Disconnected: compensations still run if the workflow is cancelled.",
      "        dc, _ := workflow.NewDisconnectedContext(ctx)",
      "        for i := len(compensations) - 1; i >= 0; i-- {",
      "            _ = compensations[i](dc)",
      "        }",
      "    }",
      "",
      "    // Step 1 — check fraud",
      "    var checkID string",
      "    if err := workflow.ExecuteActivity(ctx,",
      "        a.CheckFraud, txID, input,",
      "    ).Get(ctx, &checkID); err != nil {",
      "        runCompensations()",
      "        return result, err",
      "    }",
      "    compensations = append(compensations,",
      "        func(c workflow.Context) error {",
      "            return workflow.ExecuteActivity(c,",
      "                a.ReleaseFraudHold, txID, checkID,",
      "            ).Get(c, nil)",
      "        },",
      "    )",
      "",
      "    // Step 2 — prepare shipment",
      "    var shipmentID string",
      "    if err := workflow.ExecuteActivity(ctx,",
      "        a.PrepareShipment, txID, input, checkID,",
      "    ).Get(ctx, &shipmentID); err != nil {",
      "        runCompensations()",
      "        return result, err",
      "    }",
      "    compensations = append(compensations,",
      "        func(c workflow.Context) error {",
      "            return workflow.ExecuteActivity(c,",
      "                a.CancelShipment, txID, shipmentID,",
      "            ).Get(c, nil)",
      "        },",
      "    )",
      "",
      "    // Step 3 — charge customer",
      "    var paymentID string",
      "    if err := workflow.ExecuteActivity(ctx,",
      "        a.ChargeCustomer, txID, input, shipmentID,",
      "    ).Get(ctx, &paymentID); err != nil {",
      "        runCompensations()",
      "        return result, err",
      "    }",
      "    compensations = append(compensations,",
      "        func(c workflow.Context) error {",
      "            return workflow.ExecuteActivity(c,",
      "                a.RefundCustomer, txID, paymentID, input.Amount,",
      "            ).Get(c, nil)",
      "        },",
      "    )",
      "",
      "    // Step 4 — send confirmation",
      "    if err := workflow.ExecuteActivity(ctx,",
      "        a.SendConfirmation, txID, input,",
      "    ).Get(ctx, nil); err != nil {",
      "        runCompensations()",
      "        return result, err",
      "    }",
      "",
      '    result.Status = "completed"',
      "    return result, nil",
      "}",
    ],
    stepLines: {
      "check-fraud": [17, 31],
      "prepare-shipment": [33, 47],
      "charge-customer": [49, 63],
      "send-confirmation": [65, 71],
    },
    compLines: {
      "release-fraud-hold": [26, 30],
      "cancel-shipment": [42, 46],
      "refund-customer": [58, 62],
    },
  },
  java: {
    label: "Java",
    lines: [
      "private final Activities activities = Workflow.newActivityStub(",
      "    Activities.class,",
      "    ActivityOptions.newBuilder().setStartToCloseTimeout(Duration.ofSeconds(6)).build());",
      "",
      "@Override",
      "public OrderResult processOrder(OrderInput input) {",
      "    var txId = input.transactionId();  // reused on retries — idempotency key",
      "    var saga = new Saga(new Saga.Options.Builder().build());",
      "    try {",
      "        // Step 1 — check fraud",
      "        String checkId = activities.checkFraud(txId, input);",
      "        saga.addCompensation(",
      "            () -> activities.releaseFraudHold(txId, checkId));",
      "",
      "        // Step 2 — prepare shipment",
      "        String shipmentId = activities.prepareShipment(txId, input, checkId);",
      "        saga.addCompensation(",
      "            () -> activities.cancelShipment(txId, shipmentId));",
      "",
      "        // Step 3 — charge customer",
      "        String paymentId = activities.chargeCustomer(txId, input, shipmentId);",
      "        saga.addCompensation(",
      "            () -> activities.refundCustomer(txId, paymentId, input.amount()));",
      "",
      "        // Step 4 — send confirmation",
      "        activities.sendConfirmation(txId, input);",
      "",
      '        return new OrderResult(input.orderId(), "completed");',
      "    } catch (ActivityFailure e) {",
      "        // Detached scope: compensations still run if the workflow is cancelled.",
      "        Workflow.newDetachedCancellationScope(saga::compensate).run();",
      "        throw e;",
      "    }",
      "}",
    ],
    stepLines: {
      "check-fraud": [9, 12],
      "prepare-shipment": [14, 17],
      "charge-customer": [19, 22],
      "send-confirmation": [24, 25],
    },
    compLines: {
      "release-fraud-hold": [12, 12],
      "cancel-shipment": [17, 17],
      "refund-customer": [22, 22],
    },
  },
  typescript: {
    label: "TypeScript",
    lines: [
      'import { CancellationScope, proxyActivities } from "@temporalio/workflow";',
      'import type * as activities from "./activities";',
      "",
      "const a = proxyActivities<typeof activities>({",
      '    startToCloseTimeout: "6 seconds",',
      "});",
      "",
      "export async function orderProcessingWorkflow(",
      "    input: OrderInput,",
      "): Promise<OrderResult> {",
      "    const txId = input.transactionId;  // reused on retries — idempotency key",
      "    const compensations: Array<() => Promise<void>> = [];",
      "    try {",
      "        // Step 1 — check fraud",
      "        const checkId = await a.checkFraud(txId, input);",
      "        compensations.push(() => a.releaseFraudHold(txId, checkId));",
      "",
      "        // Step 2 — prepare shipment",
      "        const shipmentId = await a.prepareShipment(txId, input, checkId);",
      "        compensations.push(() => a.cancelShipment(txId, shipmentId));",
      "",
      "        // Step 3 — charge customer",
      "        const paymentId = await a.chargeCustomer(txId, input, shipmentId);",
      "        compensations.push(() => a.refundCustomer(txId, paymentId, input.amount));",
      "",
      "        // Step 4 — send confirmation",
      "        await a.sendConfirmation(txId, input);",
      "",
      '        return { orderId: input.orderId, status: "completed" };',
      "    } catch (err) {",
      "        // nonCancellable: compensations still run if the workflow is cancelled.",
      "        await CancellationScope.nonCancellable(async () => {",
      "            for (const c of compensations.reverse()) await c();",
      "        });",
      "        throw err;",
      "    }",
      "}",
    ],
    stepLines: {
      "check-fraud": [13, 15],
      "prepare-shipment": [17, 19],
      "charge-customer": [21, 23],
      "send-confirmation": [25, 26],
    },
    compLines: {
      "release-fraud-hold": [15, 15],
      "cancel-shipment": [19, 19],
      "refund-customer": [23, 23],
    },
  },
  python: {
    label: "Python",
    lines: [
      "@workflow.defn",
      "class OrderProcessingWorkflow:",
      "    @workflow.run",
      "    async def run(self, input: OrderInput) -> OrderResult:",
      "        tx_id = input.transaction_id  # reused on retries — idempotency key",
      "        compensations: list[Callable[[], Awaitable[None]]] = []",
      "        try:",
      "            # Step 1 — check fraud",
      "            check_id = await workflow.execute_activity(",
      "                check_fraud, args=[tx_id, input],",
      "                start_to_close_timeout=timedelta(seconds=6))",
      "            compensations.append(lambda:",
      "                workflow.execute_activity(",
      "                    release_fraud_hold, args=[tx_id, check_id],",
      "                    start_to_close_timeout=timedelta(seconds=6)))",
      "",
      "            # Step 2 — prepare shipment",
      "            shipment_id = await workflow.execute_activity(",
      "                prepare_shipment, args=[tx_id, input, check_id],",
      "                start_to_close_timeout=timedelta(seconds=6))",
      "            compensations.append(lambda:",
      "                workflow.execute_activity(",
      "                    cancel_shipment, args=[tx_id, shipment_id],",
      "                    start_to_close_timeout=timedelta(seconds=6)))",
      "",
      "            # Step 3 — charge customer",
      "            payment_id = await workflow.execute_activity(",
      "                charge_customer, args=[tx_id, input, shipment_id],",
      "                start_to_close_timeout=timedelta(seconds=6))",
      "            compensations.append(lambda:",
      "                workflow.execute_activity(",
      "                    refund_customer, args=[tx_id, payment_id, input.amount],",
      "                    start_to_close_timeout=timedelta(seconds=6)))",
      "",
      "            # Step 4 — send confirmation",
      "            await workflow.execute_activity(",
      "                send_confirmation, args=[tx_id, input],",
      "                start_to_close_timeout=timedelta(seconds=6))",
      "        except ActivityError:",
      "            async def compensate() -> None:",
      "                for c in reversed(compensations):",
      "                    await c()",
      "",
      "            # shield: compensations still run if the workflow is cancelled.",
      "            await asyncio.shield(asyncio.ensure_future(compensate()))",
      "            raise",
      "",
      '        return OrderResult(input.order_id, "completed")',
    ],
    stepLines: {
      "check-fraud": [7, 14],
      "prepare-shipment": [16, 23],
      "charge-customer": [25, 32],
      "send-confirmation": [34, 37],
    },
    compLines: {
      "release-fraud-hold": [12, 14],
      "cancel-shipment": [21, 23],
      "refund-customer": [30, 32],
    },
  },
};

// Terminal events are skipped on purpose: after a success the scan lands on
// the last step, after a failure on the last compensation that ran (or on the
// failed step when there was nothing to compensate).
const currentHighlight = computed<[number, number] | null>(() => {
  const src = SOURCES[lang.value];
  for (let i = props.events.length - 1; i >= 0; i--) {
    const env = props.events[i];
    if (!env) continue;
    if (env.type !== "progress.step.started" && env.type !== "progress.step.failed") continue;

    const step = String((env.data as Record<string, unknown>).step ?? "");
    const range = src.compLines[step] ?? src.stepLines[step];
    if (range) return range;
  }
  return null;
});
</script>

<template>
  <CodeViewer :sources="SOURCES" :highlight="currentHighlight" />
</template>
